### ISSUE TITLE
Codeforces Latest Contest Problem

### ISSUE THREAD

**Issue by Rajat119** [gaurangkeluskar22/competitive-programming#59]
@gaurangkeluskar22 Pls assign this issue to me so that I can add latest questions

**Comment by Rajat119** [comment]
Hey @gaurangkeluskar22 pls assign this to me andadd the hacktoberfest label.

**Comment by gaurangkeluskar22** [comment]
Hi @Rajat119, assigning to you.

**Comment by Rajat119** [comment]
@gaurangkeluskar22 pls add the label of hacktoberfest.

**Comment by Rajat119** [comment]
@gaurangkeluskar22 pls merge the PR and add the hacktoberfest label.

**Comment by gaurangkeluskar22** [comment]
merged
